# -*- coding: utf-8 -*-
"""Email Spam Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15o-cz3tHGJQOnTbqq25Ps3lpHGvrVb1k
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Load the dataset
data = pd.read_csv("emails.csv")

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data['text'])

X_train, X_test, y_train, y_test = train_test_split(X, data['spam'], test_size=0.2)

model = MultinomialNB()
model.fit(X_train, y_train)

yPred = model.predict(X_test)
#Evaluate the model
accuracy = accuracy_score(y_test, yPred)
print("Accuracy:", accuracy)

# Function to predict a message
def predictMessage(message):
  message = vectorizer.transform([message])
  prediction = model.predict(message)
  if prediction[0] == 1:
    print("Spam!")
  else:
    print("Not Spam!")

message = input("Enter a message to be analyzed: ")
predictMessage(message)

message = input("Enter a message to be analyzed: ")
predictMessage(message)